[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
actions_onchain = "EYj4oDQT9kwSTfwhDQwXhstE4MJ9fT1RjpwaGmqVY72f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/k/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
